name: netease-box
on:
  workflow_dispatch:
  schedule:
    - cron: '00 22 * * 0'
  push:
    branches: main
jobs:
  updateTopTracks:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
      - name: Update Gist
        uses: ./
        env:
          GIST_ID: 22c80a7dee9830ae2b6ce65d102cd517
          ACCOUNT_ID: 3900516248
          SONG_TYPE: 1
          GH_TOKEN: ${{ secrets.GH_TOKEN }}\
          
  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1
